OBJS = test1.o test2.o test3.o

mytest : $(OBJS)
# 	comment
# 	...
#	gcc -o $@ $^
	gcc -o $@ ${OBJS}

test1.o : test1.c a.h b.h
	gcc -c test1.c
# 	gcc -c $? #위험한 행위. a.h 가 갱신되면, '$ gcc -c a.h' 가 될 수 있다.

test2.o : test2.c a.h c.h
	gcc -c test2.c
# 	gcc -c $*.c #위험한 행위. a.h 가 갱신되면, '$ gcc -c a.c' 가 될 수 있다.

test3.o : test3.c a.h b.h c.h
	gcc -c test3.c
#	gcc -c $<

#phony target (dependency 없이 사용되는 target)
clean :
	-rm ${OBJS}
#  '-' 오류가 발생해도 무시하고 다음 command 진행
	-rm mytest

dep:
	gccmakedep test1.c test2.c test3.c
