SRCS = test1.c test2.c test3.c
OBJS = $(SRCS:.c=.o)
SRCS2 = exam2.c test2.c
OBJS2 = $(SRCS2:.c=.o)
SRCS3 = exam3.c test3.c
OBJS3 = $(SRCS3:.c=.o)

# cc 명령 옵션
CFLAGS = -g -Wall -O0

# ld 명령 옵션
LDFLAGS = -static -lpthread

TARGETS = mytest exam3 exam2

all: ${TARGETS}

mytest : $(OBJS)
	$(CC) -o $@ $^ ${LDFLAGS}

exam2 : $(OBJS2)
	$(CC) -o $@ $^ ${LDFLAGS}

exam3 : $(OBJS3)
	$(CC) -o $@ $^ ${LDFLAGS}

#phony target (dependency 없이 사용되는 target)
clean :
	-rm ${OBJS}
	-rm ${OBJS2} ${OBJS3}
	-rm ${TARGETS}

dep:
	gccmakedep ${SRCS}
