mytest : test1.o test2.o test3.o
	gcc -o mytest test1.o test2.o test3.o
# 	comment
# 	...
test1.o : test1.c
	gcc -c test1.c

test2.o : test2.c
	gcc -c test2.c

test3.o : test3.c
	gcc -c test3.c

#phony target (dependency 없이 사용되는 target)
clean :
	-rm test1.o test2.o test3.o
#  '-' 오류가 발생해도 무시하고 다음 command 진행
	-rm mytest

dep:
	gccmakedep test1.c test2.c test3.c
